### ISSUE TITLE
Idea: Contador de miembros Meetup

### ISSUE THREAD

**Issue by joelibaceta** [peruanosdev/peruanos.github.io#10]
Como comentaban en https://github.com/peruanosdev/peruanos.github.io/issues/7 se propuso añadir un contador de miembros de cada meetup usando el API publico de Meetup, `https://api.meetup.com/Flutter-Peru/members` (_No requiere token_), me parece que hay 2 opciones, una mas simple que otra, pero quizás menos performante.

**Opcion1:** Crear una gema de extension de Jekyll que aporte un Helper o un patrón de Markdown Custom que permita mostrar el numero de usuarios en cualquier parte del contenido.

**Opcion2:** Llamar desde JS de forma interativa y con lazy loading los miembros de cada meetup al cargar la pagina.

**Comment by 07Gond** [comment]
Había visto que en Colombia Dev tenían algo parecido.
Por lo visto en: 
https://github.com/colombia-dev/colombia-dev.github.io/blob/master/public/assets/scripts/meetupsCounter.js

Ya tienen una web corriendo con las cantidades en:
https://colombia-dev-communities.herokuapp.com
Esta también accesible desde JSON:
https://colombia-dev-communities.herokuapp.com/json

**Comment by 07Gond** [comment]
Con respecto a lo comentado creo que igual la Opcion2 sería la más rápida y fácil de hacer.

**Comment by joelibaceta** [comment]
@07Gond me aventure con la opcion1, dejo el PR https://github.com/peruanosdev/peruanos.github.io/pull/14 aunque requiere algunos consensos sobre el mecanismo de CI, me parece que si vamos por esta opción tendríamos un abanico amplio de posibilidades para añadir dinamismo.

Te dejo la demo: https://joelibaceta.github.io/peruanosdev.github.io/

**Comment by joelibaceta** [comment]
Its done :)
