### ISSUE TITLE
Idea: Mostrar lista de contribuidores

### ISSUE THREAD

**Issue by joelibaceta** [peruanosdev/peruanos.github.io#15]
Podríamos incluir la lista de top `contributors` del repo, para fomentar los PRs

![PeruanosDevWithContributors](https://user-images.githubusercontent.com/864790/60617650-c3ad9180-9d99-11e9-8a8f-c9bb83771dc5.png)

Esto se puede hacer consultando al siguiente API sin autenticación: 
https://api.github.com/repos/peruanosdev/peruanos.github.io/contributors

**Resultado:**

```json
[
    {
        "login": "hacksy",
        "id": 33564005,
        "node_id": "MDQ6VXNlcjMzNTY0MDA1",
        "avatar_url": "https://avatars1.githubusercontent.com/u/33564005?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hacksy",
        "html_url": "https://github.com/hacksy",
        "followers_url": "https://api.github.com/users/hacksy/followers",
        "following_url": "https://api.github.com/users/hacksy/following{/other_user}",
        "gists_url": "https://api.github.com/users/hacksy/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/hacksy/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/hacksy/subscriptions",
        "organizations_url": "https://api.github.com/users/hacksy/orgs",
        "repos_url": "https://api.github.com/users/hacksy/repos",
        "events_url": "https://api.github.com/users/hacksy/events{/privacy}",
        "received_events_url": "https://api.github.com/users/hacksy/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 15
    },
    ...
]
```

**Comment by 07Gond** [comment]
👍 a la idea.
Sería bueno poder implementarlo creo.

@eporroa @hpneo @hacksy 
opiniones?

**Comment by darksy12** [comment]
Sip, se ve bien

**Comment by joelibaceta** [comment]
@07Gond @darksy12 ok :) mas tarde mando PR

**Comment by 07Gond** [comment]
@joelibaceta algún update?

**Comment by joelibaceta** [comment]
@07Gond este PR sigue abierto :c https://github.com/peruanosdev/peruanos.github.io/pull/14

**Comment by joelibaceta** [comment]
@07Gond :D por fin se impactaron los cambios ahora me pongo a trabajar en esto

**Comment by ivandevp** [comment]
@joelibaceta sugiero seguir algo un poco más estándar como https://github.com/all-contributors/all-contributors, tiene un CLI y un bot que se puede agregar al workflow para q sea un poco más automatizado.

**Comment by joelibaceta** [comment]
@ivandevp lo reviso, actualmente ya tenemos un workflow de CI :)

**Comment by paulotijero** [comment]
@07Gond @joelibaceta existe algún motivo por el que este issue sigue abierto? :thinking: es que me pareció ver estos cambios ya en producción.

**Comment by joelibaceta** [comment]
@paulotijero es cierto, ahi lo cierro
