### ISSUE TITLE
Idea: Tener una alternativa dark mode

### ISSUE THREAD

**Issue by joelibaceta** [peruanosdev/peruanos.github.io#17]
Ya que esta moda podríamos disponer de una versión Dark según elección ( Solo funcionaria en Mac 🤷‍♂️ )

![PeruanosDevDark](https://user-images.githubusercontent.com/864790/60627078-93262180-9db2-11e9-9e06-64d155abb7ac.png)

Sugiero usar media queries

```css
@media (prefers-color-scheme: dark) {

}
```

**Comment by darksy12** [comment]
Solo es poner esa linea? si es asi yo le voy

**Comment by 07Gond** [comment]
@hacksy go

**Comment by condef5** [comment]
I'm gonna take this issue.
