### ISSUE TITLE
Idea: Columna con scroll interno

### ISSUE THREAD

**Issue by joelibaceta** [peruanosdev/peruanos.github.io#21]
Pensaba quizás que estaría bueno tener la columna con la info de peruanos.dev estática siempre presente y hacer que el contenido sea scrolleable (en versión desktop), algo así, que opinan?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/864790/60771795-23ba7580-a0c3-11e9-9646-44d60c162fed.gif)

**Comment by 07Gond** [comment]
Me gusta, es buena idea. 👍

**Comment by darksy12** [comment]
A mi tambien, go :D
