### ISSUE TITLE
Idea: pagina unica

### ISSUE THREAD

**Issue by joelibaceta** [peruanosdev/peruanos.github.io#3]
Hola!, propongo hacer un par de cambios menores para integrar la lista de comunidades con la pagina principal, esto con el fin de simplificar el sitio.

**Cambios propuestos:**

- Hacer un fork del tema `minima` usado por Jekyll según la configuración actual, en este `Fork` se puede alterar la estructura del layout principal.
- Incluir la lista de comunidades como parte de la pagina principal, permitiendo una exploración directa, **ejem**: https://commits.top/argentina.html
- Modificar el archivo `Gemfile` para usar el tema de la gema `minima` modificada alojada en el `Fork`.

**Boceto de layout:**

![minima-white](https://user-images.githubusercontent.com/864790/59984372-01b6f280-95ef-11e9-8d23-4613a6826b97.png)

Quedo atento a sus comentarios, si les gusta la idea podría enviar un PR, todo esta abierto a discusión.

**Comment by 07Gond** [comment]
Gracias @joelibaceta por la idea!
Me gusta. Sobretodo el fixed de la presentación y lo limpio que es.
Me pregunto si también sería buena idea agregar la cantidad de usuarios que tienen los Meetups respectivamente.
No tengo mucha experiencia con Jekyll así que etiqueto a @hpneo para escuchar sus comentarios también :)

**Comment by joelibaceta** [comment]
@07Gond eso se podria gestionar con el [API de Meetup](https://www.meetup.com/es-ES/meetup_api/docs/2/members/?uri=%2Fmeetup_api%2Fdocs%2F2%2Fmembers%2F), de forma que sea menos manual.

**Comment by hpneo** [comment]
@07Gond @joelibaceta se ve bien el diseño propuesto, aunque también puedes crear layouts y css que sobreescriba lo que da Minima, pero depende de ti (personalmente preferiría esto para no tener que lidiar con el mantenimiento de un theme de Jekyll aparte de un site).

Sobre agregar el número de usuarios por meetup, no estoy seguro cómo podría hacerse de forma que sea soportado por Jekyll (AFAIK solo soportan contenido estático), pero sería genial que armes un PR para revisarlo.

**Comment by joelibaceta** [comment]
@hpneo @07Gond hice una demo en el gh-pages del fork siguiendo la sugerencia de usar layouts y css dentro del mismo repo https://joelibaceta.github.io/peruanosdev.github.io/ , si están ok, mando PR

**Comment by joelibaceta** [comment]
@hpneo se puede añadir dinamismo creando una gema como extension de Jekyll y disponibilizar el contador de miembros como un helper de erb o markdown enriquecido , yo suelo usar mas el segundo para facilitar el mantenimiento, es decir registrar un regex para un componente markdown personalizado.

**Ejemplo:**
`[[[counter-meetup-members: GDGChimbote]]]`

> Este se procesaria al generar los estáticos en cada deploy para imprimir el numero de miembros, actualizandose automáticamente.

**Comment by joelibaceta** [comment]
@hpneo no se que tan lento es el API de Meetup, pero por JS también se podria consultar a `https://api.meetup.com/{{meetup-group-url-name}}/members`, la llamada no requiere un API Key

**Comment by hpneo** [comment]
@joelibaceta se ve cortado en mobile:
![joelibaceta github io_peruanosdev github io_(iPhone X)](https://user-images.githubusercontent.com/611699/60030780-35cef980-9669-11e9-8ba3-44748a073596.png)

![joelibaceta github io_peruanosdev github io_(iPhone X) (1)](https://user-images.githubusercontent.com/611699/60030839-4c755080-9669-11e9-9827-c95247dc37e3.png)

**Comment by joelibaceta** [comment]
@hpneo lo reviso

**Comment by joelibaceta** [comment]
@hpneo resuelto 

<img width="710" alt="Captura de Pantalla 2019-06-24 a la(s) 14 03 42" src="https://user-images.githubusercontent.com/864790/60044844-e4366700-9688-11e9-89f7-abb99f9f43b4.png">

**Comment by hpneo** [comment]
👍 manda PR para revisarlo y mergearlo.

**Comment by joelibaceta** [comment]
PR: https://github.com/peruanosdev/peruanos.github.io/pull/8

**Comment by joelibaceta** [comment]
@hpneo PR enviado. 👍

**Comment by hpneo** [comment]
Merged.
