### ISSUE TITLE
Agregar FB Link a las comunidades

### ISSUE THREAD

**Issue by darksy12** [peruanosdev/peruanos.github.io#38]
Algunas comunidades no usan solo meetup , si no tambien facebook, podemos agregar un link a su FB Community

**Comment by joelibaceta** [comment]
@darksy12 podría usarse una integración con FB para poder extraer data de Facebook, pasa que ahora el script de building cuando encuentra un error al extraer data del API de Meetup, se salta esa comunidad XD

**Comment by 07Gond** [comment]
Si no hay viabilidad lo cerramos? @joelibaceta @darksy12 ?

**Comment by joelibaceta** [comment]
Si :c
