### ISSUE TITLE
Idea: Cambiar link 'pull request' por el editar online del archivo communities.json

### ISSUE THREAD

**Issue by joelibaceta** [peruanosdev/peruanos.github.io#4]
Para simplificar la colaboración, considerando que no hay un **contributors guide**, quizás podría redirigirse el link de `pull request` para agregar comunidades que ahora lleva al repo, por uno que dirija automáticamente al editor en linea del archivo `communities.json` https://github.com/peruanosdev/peruanos.dev/edit/master/_data/communities.json

**Comment by darksy12** [comment]
Estaría mejor escribir una guía de contribuidor, no ?

**Comment by joelibaceta** [comment]
@hacksy depende 🤷‍♂️, yo veo 2 tipos de contribuidor ( _es cierto que ambos deberían ser devs familiarizados con GitHub, pero no asumiría eso_ ):

1. El que solo quiere proponer un Meetup ( _No necesariamente es tecnico, podría ser un miembro de un meetup_ )
2. El que quiere contribuir con el desarrollo de nuevos features o mejoras sobre el sitio. (_Este si es tecnico y va a leer el contributors guide_) 

Por lo que me parece que podríamos tener ambas opciones, el icono en la esquina de send a Pull Request, algo asi.

<img width="377" alt="Captura de Pantalla 2019-06-24 a la(s) 09 09 35" src="https://user-images.githubusercontent.com/864790/60025709-d28c9980-965f-11e9-83cd-88e99fc070b5.png">

Y el botón, agrega tu meetup, que te lleve directamente a la edicion del json de la lista de meetups.

**Comment by 07Gond** [comment]
Creo que la gran mayoría de usuarios son devs al pertenecer a comunidades devs. Difícil que alguien no sepa cómo usar Github. Pero entiendo que la complejidad del CONTRIBUTING podría ser más alta.

Dicho esto, me gusta la idea de agregar el botón de "_Contribute to this project_".
Me gustaría ver cómo quedaría el diseño con respecto a esto.

Con respecto al botón de agrega tu meetup te refieres a mandarle el link de https://github.com/peruanosdev/peruanos.github.io/edit/master/_data/communities.json ?

El diseño del ícono y botón de este último también debería ser blanco y negro para guardar uniformidad.

**Comment by 07Gond** [comment]
Esto, claro, no quita que también sería bueno tener un README.md y un CONTRIBUTING.md que es lo que también mencionó @hacksy

**Comment by joelibaceta** [comment]
Si, algo asi podría ser el botón de `contribute to this project`

![TwoColumnsContribute](https://user-images.githubusercontent.com/864790/60061811-3c3a9100-96bc-11e9-91e2-a923cd59884f.png)

Sobre lo del agregar el meetup, si igual podria no ser un botón o si, pero efectivamente proponía que se dirija directamente al editor online para el archivo `communities.json`.

**Comment by joelibaceta** [comment]
@07Gond que opinas ?

**Comment by 07Gond** [comment]
@joelibaceta disculpa que estaba terminando mis vacaciones.
Ahora, sí me gusta ese diseño y la idea. Hagámoslo!

**Comment by joelibaceta** [comment]
@07Gond agregue el botón aqui https://github.com/peruanosdev/peruanos.github.io/pull/12

**Demo:** https://joelibaceta.github.io/peruanosdev.github.io/

**Comment by joelibaceta** [comment]
@07Gond no se actualizo el sitio me parece.

**Comment by 07Gond** [comment]
Sí, me ha mandado Github una notificación de un problema con el CNAME. 
Raro.

**Comment by joelibaceta** [comment]
@07Gond pudiste ver esto?, crees que se deba reabrir el issue ?

**Comment by 07Gond** [comment]
No creo que se reabra el issue porque no está directamente relacionado.
Mas bien voy a crear otro issue para poder ver el tema.
Gracias por el reminder!
