### ISSUE TITLE
Añadir indicador de eventos llenos

### ISSUE THREAD

**Issue by joelibaceta** [peruanosdev/peruanos.github.io#40]
Añadir un indicador de que la capacidad de un evento ya ha sido superada.

Se me ocurre tener algo como 12/50 y luego un badge que diga “waitlist” o “full”

**Comment by paulotijero** [comment]
Tengo una opinión un tanto desalentadora, ya que normalmente se inscriben `N` personas a un evento y solo asisten un promedio de `N/2`, creo que esto solo aumentaría el numero de inasistencia por pensar que ya estan `"full"` :thinking:

**Comment by joelibaceta** [comment]
@paulotijero hay varios puntos de vista en realidad: 
- Como organizador de evento si se que de 100 llegan 50, abro 200 espacios.
- Como asistente si ya estoy en un waitlist probablemente no asista.
- Se fomenta nuevos registros al ver que quedan solo 3 lugares para un evento
- Se fomenta que los organizadores tengan una mejor planificación de espacios

**Contras:**
- Efectivamente el ver que dan pocos lugares podría generar falsos registros motivados solo por el numero en lugar del interés

**Comment by joelibaceta** [comment]
Que dices @07Gond ? @darksy12?

**Comment by darksy12** [comment]
A mi si me parece interesante, ya tenemos descripcion y link, para evitar clicks sin sentido

**Comment by 07Gond** [comment]
Me gusta la idea.
