### ISSUE TITLE
Bug: Sobreescritura de contenido bajo dominio peruanos.dev

### ISSUE THREAD

**Issue by joelibaceta** [peruanosdev/peruanos.github.io#5]
Al parecer cuando el **CNAME** esta dentro del repo, desde un Fork se puede sobre escribir el sitio web original lo cual hace que el sitio sea vulnerable, ya que este también contiene la configuración de dominio.

**Prueba:**  (Estado de sitio actual)
<img width="1003" alt="Captura de Pantalla 2019-06-24 a la(s) 05 25 36" src="https://user-images.githubusercontent.com/864790/60011977-80884b80-9640-11e9-936a-018e45818f97.png">

**Como reproducir el Bug**
1.- Hacer un `Fork` del repositorio
2.- Configurar el despliegue automatico de `GitHub-Pages` a partir de master para el `Fork`
3.- Realizar un cambio y actualizar la rama master del `Fork` para lanzar un `deploy` nuevo.
4.- Ir al dominio **peruanos.dev** registrado para y comprobar que el contenido ha sido actualizado mostrando el contenido del Fork y no el original.
5.- Si se retira el archivo .CNAME o se cambia la configuración, se obtiene un 404 como se ve en la prueba.

**Comment by darksy12** [comment]
Aparentemente rompiste github pages . Ya lo "arregle" pero preguntaremos si hay solucion

**Comment by joelibaceta** [comment]
@hacksy efectivamente, era cuestión de que en algún momento cambiaron o dejaron en blanco el dominio y lo tome desde la config del fork (_no se si debería poderse_) y cuando borre la conf ya pudieron recuperarlo, ahora ya me sale un alert de que no se puede 👍, cierro issue

<img width="741" alt="Captura de Pantalla 2019-06-24 a la(s) 09 38 04" src="https://user-images.githubusercontent.com/864790/60028154-711af980-9664-11e9-9e83-9ca4067b1104.png">
