### ISSUE TITLE
Migración a un SPA

### ISSUE THREAD

**Issue by lperezp** [peruanosdev/peruanos.github.io#53]
Hola!, propongo hacer unos cambios, esto con el fin de simplificar  y que esté activo el sitio con información actualizada.

**Cambios propuestos:**

- Hacer un fork de la rama `master`, en este `Fork` se puede alterar la estructura del layout principal.
- Hacer un SPA con Angular para que el rendimiento sea mejor.

**Boceto de layout en desktop:**

![Desktop - 1](https://github.com/peruanosdev/peruanos.github.io/assets/16889854/380641e4-19c5-4a50-952f-6f74a330d6a2)

**Boceto de layout en mobile:**

![iPhone 14   15 Pro Max - 1](https://github.com/peruanosdev/peruanos.github.io/assets/16889854/39bdcda0-41f6-4b77-9af5-e1696add8480)

Quedo atento a sus comentarios, si les gusta la idea podría enviar un PR, todo esta abierto a discusión.

**Comment by joelibaceta** [comment]
Like 👍 se ve muy bueno, solo quizas pondria a los colaboradores en la version web arriba estilo github ( top 10 o 15 ) debajo de la descripcion, como circulitos asi el scroll puede ser infinito

**Comment by lperezp** [comment]
Tomando la idea, quedaría así. Lo veo mucho mejor! 

![image](https://github.com/peruanosdev/peruanos.github.io/assets/16889854/5f098436-7f41-4dad-ab42-05f30c6941ab)

**Comment by joelibaceta** [comment]
Si creo que se ve bien

**Comment by lperezp** [comment]
Existe ya una rama con los cambios.  [migration-to-spa](https://github.com/peruanosdev/peruanos.github.io/tree/migration-to-spa).

Faltaría agregar la opción cambiar de tema a dark y que el json sea actualizado por las comunidades.
