### ISSUE TITLE
Idea: Calendario de eventos

### ISSUE THREAD

**Issue by joelibaceta** [peruanosdev/peruanos.github.io#7]
Según la propuesta de calendario de eventos por sugerencia de @eporroa ayer hice un experimento para meetups de BA ( https://joelibaceta.github.io/meetups-calendar/ ), podría hacer un PR para incluirlo en el sitio con los meetups de Lima. ( _En lo personal me gustaría hacerlo como una tercera columna del [diseño unificado](https://github.com/peruanosdev/peruanos.github.io/issues/3) que propuse_ ), no se que opinan?

![next_events](https://user-images.githubusercontent.com/864790/60031881-20f36580-966b-11e9-8fa2-8185809b17ad.png)

**Comment by 07Gond** [comment]
A mí me gusta mucho esta idea.
No estoy de seguro si sería al lado o abajo pero podrías comenzar de esta manera.
Y también me gustaría ver cómo quedaría en mobile.
@peruanosdev/everyone qué opinan?

**Comment by darksy12** [comment]
se ve muy bien , aunque quizá 5 eventos cercanosen el home y el calendar completo en otra pagina

**Comment by joelibaceta** [comment]
@hacksy yo evitaria hacer mas de 1 pagina, para mantener la simplicidad del proyecto, podría ser otro proyecto de calendario de eventos y extraer el **community.json** a otro repo que pueda usarse como submodule de cualquier proyecto que quiera usar esa fuente de datos.

**Comment by 07Gond** [comment]
IMO, cualquiera de las dos opciones me gustan.
Me gustaría ver primero los 5 meetups más cercanos al menos como primera versión.
@peruanosdev/everyone qué opinan?

**Comment by joelibaceta** [comment]
@07Gond este PR https://github.com/peruanosdev/peruanos.github.io/pull/14 podría ser un approach para resolver esto también.

**Comment by 07Gond** [comment]
Pero @joelibaceta en el #14 no se ve un calendario. 🤔

**Comment by joelibaceta** [comment]
Me referia al approach de generar el calendario usando un plugin en tiempo de generación de estáticos.

**Comment by 07Gond** [comment]
@joelibaceta Dale, entonces esperemos que se mergee pronto el otro PR para luego poder realizar el plugin del calendario.
💯

**Comment by joelibaceta** [comment]
![CKT9D1zUcAAmJXd](https://user-images.githubusercontent.com/864790/63810313-18790e80-c8ea-11e9-8934-f52d293c287e.png)
