### ISSUE TITLE
Idea: Simplificación + Vectorización de logo

### ISSUE THREAD

**Issue by joelibaceta** [peruanosdev/peruanos.github.io#9]
Como ninguno de nosotros somos diseñadores por aquí, me tome la libertad de hacer una atrevida propuesta, desde el desconocimiento de la rama, trate de simplificar el logo, estoy abierto a cualquier sugerencia e idea ya que me tome el tiempo de vectorizarlo podría añadir cambios sin problema.

**Propuesta de mejora:** 
- Vectorizado
- Mas espaciado
- Un tono ligeramente mas claro de fondo

<img width="772" alt="Captura de Pantalla 2019-06-24 a la(s) 19 34 47" src="https://user-images.githubusercontent.com/864790/60060636-28406080-96b7-11e9-85a9-e72c3864a5fb.png">

```
     Propuesta   SVG              Anterior   JPEG              Rojo   SVG
```

**Comment by 07Gond** [comment]
Ni lo había pensado en rojo.
Queda genial!

La verdad es que tampoco tengo vista de diseñador pero el bold en el **dev** creo que acentúa bien lo que proponemos.

De todas formas creo que hubo un cambio de fuente cierto? No recuerdo la fuente con la que estaba(my bad!), lo puedo buscar pero creo que me gusta más la fuente anterior que la propuesta.

Por el espaciado y el vectorizado, queda bien.
Gracias! @joelibaceta

**Comment by 07Gond** [comment]
@eporroa @hpneo @hacksy qué opinan?

**Comment by carlosgub** [comment]
Podria ser con mas grosor la llama ? creo que ayudaria un poco :D

**Comment by joelibaceta** [comment]
Podría probar, voy a buscar el vectorial :)

**Comment by 07Gond** [comment]
@joelibaceta Hola, llegaste a probarlo?

**Comment by joelibaceta** [comment]
@07Gond ahora lo pruebo :)

**Comment by joelibaceta** [comment]
Bordes 0, 1 y 2
<img width="939" alt="Captura de Pantalla 2019-10-12 a la(s) 21 48 17" src="https://user-images.githubusercontent.com/864790/66710241-02100080-ed3a-11e9-9586-6969410e36a4.png">

**Comment by 07Gond** [comment]
Me gusta el 2.
@darksy12 qué opinas?
